"use client";

import { useCoAgent } from "@copilotkit/react-core";
import { CopilotChat } from "@copilotkit/react-ui";
import "@copilotkit/react-ui/styles.css";
import { useEffect, useLayoutEffect, useState } from "react";

import AuditDashboardContent from "@/components/dashboard/AuditDashboardContent";
import MethodologyModal from "@/components/MethodologyModal";
import { useGeoAuditCopilot } from "@/hooks/useGeoAuditCopilot";
import { GeoAuditState } from "@/lib/types";

type AppLocale = "it" | "en";

const SOCIAL_LINKS = {
  discord: "https://discord.com",
  linkedin: process.env.NEXT_PUBLIC_LINKEDIN_URL ?? "https://www.linkedin.com/in/rossi-stefano/",
  bug: process.env.NEXT_PUBLIC_FEEDBACK_FORM_URL ?? "https://github.com/geo-audit/issues/new",
};

const UI_TEXT: Record<AppLocale, {
  copilotReadable: string;
  loadingScore: string;
  loadingCrawlers: string;
  loadingPlan: string;
  loadingLlms: string;
  loadingSchema: string;
  subtitle: string;
  scoreLabel: string;
  runningPrefix: string;
  noAuditTitle: string;
  noAuditBody: string;
  samplePrompt1: string;
  samplePrompt2: string;
  chatTitle: string;
  chatInitial: string;
  aiActLabel: string;
  socialDiscord: string;
  socialLinkedin: string;
  socialBug: string;
  topBanner: string;
}> = {
  it: {
    copilotReadable: "Stato corrente audit GEO: URL, punteggi e risultati",
    loadingScore: "Calcolo GEO score in corso...",
    loadingCrawlers: "Analisi accesso crawler in corso...",
    loadingPlan: "Costruzione action plan in corso...",
    loadingLlms: "Generazione llms.txt in corso...",
    loadingSchema: "Verifica schema markup in corso...",
    subtitle: "Generative Engine Optimization experimental app · powered by LangGraph + CopilotKit",
    scoreLabel: "Punteggio GEO",
    runningPrefix: "Analisi in corso",
    noAuditTitle: "Nessun audit in corso",
    noAuditBody:
      "Usa la chat a destra: scrivi una richiesta con URL completo e premi invio. L'assistente avviera automaticamente l'audit e questa dashboard si aggiornera con score, criticita e piano d'azione.",
    samplePrompt1: '"Fai un audit GEO di https://www.examplebank.it/banca-on-line"',
    samplePrompt2: '"Analizza https://www.miosito.it e dammi top 3 problemi + quick win"',
    chatTitle: "GEO Audit Assistant",
    chatInitial:
      "Ciao! Incolla direttamente qui l'URL completo del sito e chiedimi l'audit GEO.\n\nEsempio: Fai un audit GEO di https://www.example.com\n\nAnalizzero: AI crawler access, llms.txt, schema markup, meta tag e citability score.",
    aiActLabel:
      "AI Disclosure (EU AI Act): questa risposta e generata da un sistema di AI e puo contenere errori o imprecisioni. Verifica sempre le informazioni critiche.",
    socialDiscord: "Discord",
    socialLinkedin: "LinkedIn",
    socialBug: "Feedback, bug ed evolutive",
    topBanner:
      "Nuovo: supporto bilingue IT/EN attivo. La lingua viene scelta automaticamente dal browser.",
  },
  en: {
    copilotReadable: "Current GEO audit state: URL, scores, and findings",
    loadingScore: "Calculating GEO score...",
    loadingCrawlers: "Analyzing crawler access...",
    loadingPlan: "Building action plan...",
    loadingLlms: "Generating llms.txt...",
    loadingSchema: "Checking schema markup...",
    subtitle: "Generative Engine Optimization experimental app · powered by LangGraph + CopilotKit",
    scoreLabel: "GEO Score",
    runningPrefix: "Analysis in progress",
    noAuditTitle: "No audit in progress",
    noAuditBody:
      "Use the chat on the right: submit a prompt with the full URL and press enter. The assistant will automatically start the audit and this dashboard will update with score, issues, and action plan.",
    samplePrompt1: '"Run a GEO audit for https://www.examplebank.it/banca-on-line"',
    samplePrompt2: '"Analyze https://www.mysite.com and give me top 3 issues + quick wins"',
    chatTitle: "GEO Audit Assistant",
    chatInitial:
      "Hi! Paste the full website URL here and ask me to run a GEO audit.\n\nExample: Run a GEO audit for https://www.example.com\n\nI will analyze: AI crawler access, llms.txt, schema markup, meta tags, and citability score.",
    aiActLabel:
      "AI Disclosure (EU AI Act): this response is generated by AI and may contain errors or inaccuracies. Always verify critical information.",
    socialDiscord: "Discord",
    socialLinkedin: "LinkedIn",
    socialBug: "Feedback, bugs & feature requests",
    topBanner:
      "New: bilingual IT/EN support is enabled. Language is selected automatically from your browser.",
  },
};

function detectLocale(): AppLocale {
  if (typeof navigator === "undefined") {
    return "en";
  }
  return navigator.language.toLowerCase().startsWith("it") ? "it" : "en";
}

// ---------------------------------------------------------------------------
// Main Page
// ---------------------------------------------------------------------------
export default function Home() {
  const [locale, setLocale] = useState<AppLocale>("en");
  const [showMethodology, setShowMethodology] = useState(false);

  useEffect(() => {
    const nextLocale = detectLocale();
    setLocale(nextLocale);
    document.documentElement.lang = nextLocale;
  }, []);

  useLayoutEffect(() => {
    const hideInspector = () => {
      document
        .querySelectorAll<HTMLElement>('cpk-web-inspector, button[aria-label="Web Inspector"], .console-button')
        .forEach((element) => {
          element.remove();
        });
    };

    hideInspector();
    const intervalId = window.setInterval(hideInspector, 500);

    const observer = new MutationObserver(() => {
      hideInspector();
    });

    observer.observe(document.body, { childList: true, subtree: true });

    return () => {
      window.clearInterval(intervalId);
      observer.disconnect();
    };
  }, []);

  const t = UI_TEXT[locale];

  const { state } = useCoAgent<GeoAuditState>({
    name: "default",
    initialState: {
      url: "",
      status: "idle",
      messages: [],
    },
  });

  useGeoAuditCopilot({
    state,
    locale,
    labels: {
      copilotReadable: t.copilotReadable,
      loadingScore: t.loadingScore,
      loadingCrawlers: t.loadingCrawlers,
      loadingPlan: t.loadingPlan,
      loadingLlms: t.loadingLlms,
      loadingSchema: t.loadingSchema,
    },
  });

  const hasReport = Boolean(state.report);

  return (
    <div className="app-shell flex min-h-screen flex-col overflow-x-hidden overflow-y-visible text-slate-100 lg:h-screen lg:flex-row lg:overflow-hidden">

      {/* ── Left: Dashboard ─────────────────────────────────────────────── */}
      <div className="min-w-0 flex-1 overflow-visible p-4 sm:p-5 md:p-7 lg:overflow-y-auto">
        <div className="glass-panel rounded-[1.75rem] p-4 sm:p-5 md:rounded-3xl md:p-7">
          {/* Header */}
          <header className="mb-6 flex flex-col items-start gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div className="min-w-0 flex-1">
              <h1 className="text-2xl md:text-3xl font-semibold tracking-tight shimmer-text">GEO Audit Agent</h1>
              <p className="mt-1 max-w-2xl text-sm text-slate-300/80 sm:text-[15px]">
                {t.subtitle}
              </p>
              <button
                onClick={() => setShowMethodology(true)}
                className="mt-2 inline-flex items-center gap-1.5 glass-chip social-chip rounded-lg px-2.5 py-1.5 text-xs text-cyan-300"
                aria-label={locale === "it" ? "Come vengono calcolati i KPI" : "How KPIs are calculated"}
              >
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><circle cx="12" cy="12" r="10" /><path d="M12 16v-4M12 8h.01" /></svg>
                {locale === "it" ? "Come si calcolano i KPI" : "How KPIs are calculated"}
              </button>
              <div className="mt-3 flex flex-wrap items-center gap-2">
                <a
                  href={SOCIAL_LINKS.discord}
                  target="_blank"
                  rel="noreferrer"
                  className="glass-chip social-chip rounded-lg px-2.5 py-1.5 text-xs text-slate-200"
                  aria-label={t.socialDiscord}
                  title={t.socialDiscord}
                >
                  <span className="inline-flex items-center gap-1.5">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M20.32 4.37A19.79 19.79 0 0 0 15.4 3l-.24.49a18.3 18.3 0 0 1 4.43 2.13 14.32 14.32 0 0 0-3.71-1.18 18.37 18.37 0 0 0-3.88-.02A14.15 14.15 0 0 0 8.29 5.6a18.02 18.02 0 0 1 4.41-2.11L12.46 3a19.68 19.68 0 0 0-4.93 1.38C4.55 8.9 3.79 13.31 4.03 17.66a19.9 19.9 0 0 0 5.99 3.03l.49-.81a12.98 12.98 0 0 1-1.89-.9l.47-.35c3.64 1.71 7.57 1.71 11.17 0l.47.35c-.6.35-1.24.66-1.9.9l.49.81a19.8 19.8 0 0 0 6-3.03c.28-5.04-.48-9.45-3.5-13.29ZM9.68 15.02c-1.09 0-1.98-.99-1.98-2.22s.87-2.23 1.98-2.23c1.12 0 2 1 1.98 2.23 0 1.23-.88 2.22-1.98 2.22Zm4.64 0c-1.09 0-1.98-.99-1.98-2.22s.87-2.23 1.98-2.23c1.12 0 2 1 1.98 2.23 0 1.23-.88 2.22-1.98 2.22Z" /></svg>
                    {t.socialDiscord}
                  </span>
                </a>
                <a
                  href={SOCIAL_LINKS.linkedin}
                  target="_blank"
                  rel="noreferrer"
                  className="glass-chip social-chip rounded-lg px-2.5 py-1.5 text-xs text-slate-200"
                  aria-label={t.socialLinkedin}
                  title={t.socialLinkedin}
                >
                  <span className="inline-flex items-center gap-1.5">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M6.94 8.5H3.56V20h3.38V8.5ZM5.25 3A1.97 1.97 0 0 0 3.28 4.97c0 1.09.88 1.97 1.97 1.97s1.97-.88 1.97-1.97A1.97 1.97 0 0 0 5.25 3ZM20.72 12.72c0-2.84-1.52-4.16-3.55-4.16-1.63 0-2.36.9-2.77 1.53V8.5H11V20h3.4v-5.7c0-1.5.28-2.95 2.14-2.95 1.83 0 1.86 1.72 1.86 3.05V20H22v-7.28Z" /></svg>
                    {t.socialLinkedin}
                  </span>
                </a>
                <a
                  href={SOCIAL_LINKS.bug}
                  target="_blank"
                  rel="noreferrer"
                  className="glass-chip social-chip rounded-lg px-2.5 py-1.5 text-xs text-rose-100"
                  aria-label={t.socialBug}
                  title={t.socialBug}
                >
                  <span className="inline-flex items-center gap-1.5">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M8 2h8l1 3h2v2h-2.1l-.9 10a2 2 0 0 1-2 1.8H10a2 2 0 0 1-2-1.8L7.1 7H5V5h2l1-3Zm2.2 3h3.6l-.34-1H10.5l-.3 1ZM9 21h6" /><path d="M12 9v6M9.5 11h5" /></svg>
                    {t.socialBug}
                  </span>
                </a>
              </div>
            </div>
            {hasReport && state.geo_score !== undefined && (
              <div className="w-full self-stretch text-left glass-chip score-badge-hover glow-pulse rounded-xl px-3 py-2 sm:w-auto sm:self-start sm:text-right">
                <p className="text-[11px] text-slate-300/80 uppercase tracking-wider">{t.scoreLabel}</p>
                <p
                  className="text-3xl font-bold"
                  style={{
                    color: state.geo_score >= 70 ? "#2dd4bf"
                      : state.geo_score >= 45 ? "#fbbf24"
                        : "#fb7185",
                  }}
                >
                  {state.geo_score}<span className="text-lg text-slate-400">/100</span>
                </p>
              </div>
            )}
          </header>

          <AuditDashboardContent
            state={state}
            locale={locale}
            text={{
              runningPrefix: t.runningPrefix,
              noAuditTitle: t.noAuditTitle,
              noAuditBody: t.noAuditBody,
              samplePrompt1: t.samplePrompt1,
              samplePrompt2: t.samplePrompt2,
            }}
            defaultLlmsTxt={DEFAULT_LLMS_TXT[locale]}
          />
        </div>
      </div>

      {/* ── Methodology Modal ────────────────────────────────────────────── */}
      <MethodologyModal
        open={showMethodology}
        onClose={() => setShowMethodology(false)}
        locale={locale}
      />

      {/* ── Right: CopilotKit Chat ───────────────────────────────────────── */}
      <div className="w-full shrink-0 p-4 pt-0 sm:px-5 md:px-7 md:pb-7 lg:w-[26rem] lg:p-5 xl:w-[28rem]">
        <div className="glass-panel-strong flex h-[min(42rem,72vh)] min-h-[28rem] flex-col overflow-hidden rounded-[1.75rem] lg:h-full lg:min-h-0 lg:rounded-3xl">
          <div className="mx-3 mt-3 mb-2 rounded-lg border border-amber-300/30 bg-amber-200/10 px-3 py-2 text-[11px] leading-relaxed text-amber-100">
            {t.aiActLabel}
          </div>
          <CopilotChat
            labels={{
              title: t.chatTitle,
              initial: t.chatInitial,
            }}
            className="h-full min-h-0"
          />
        </div>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Default llms.txt template (shown when site doesn't have one)
// ---------------------------------------------------------------------------
const DEFAULT_LLMS_TXT: Record<AppLocale, string> = {
  it: `# Organizzazione — Informazioni per i Modelli AI

## Chi Siamo
[Nome organizzazione] offre [breve descrizione dei servizi].
Fondata nel [anno], [differenziatore principale].

## Servizi
- [Servizio 1]
- [Servizio 2]
- [Servizio 3]

## Fatti Chiave
- Sede: [Citta, Paese]
- Fondazione: [Anno]
- Licenze / Certificazioni: [Credenziali rilevanti]

## Pagine Importanti
- Sito principale: https://www.example.com
- Contatti: https://www.example.com/contact
- Supporto: https://www.example.com/help

## Citazione Preferita
Quando ci citi, usa: "[Nome organizzazione] (www.example.com)"

## Termini
- Informazioni fornite a solo scopo informativo`,
  en: `# Organization — AI Model Information

## About
[Your organization name] provides [brief description of services].
Founded in [year], we [key differentiator].

## Services
- [Service 1]
- [Service 2]
- [Service 3]

## Key Facts
- Headquarters: [City, Country]
- Founded: [Year]
- License / Certification: [Relevant credentials]

## Important Pages
- Main site: https://www.example.com
- Contact: https://www.example.com/contact
- Help: https://www.example.com/help

## Preferred Citation
When referencing us, please cite as: "[Organization name] (www.example.com)"

## Terms
- Information provided for reference purposes only
- Copyright © [Organization name]
`,
};
